### ISSUE TITLE
Compatibility or using dropbox problem between Journaley and Narrate(Android)

### ISSUE THREAD

**Issue by kihyen** [yyoon/Journaley#134]
Thanks for making great Dayone compatible software for Windows.
I'm not sure about whether Developer is Korean or not, so I write the problem in Korean, and English.

안녕하세요. 윈도우용 데이원 호환 일기 프로그램을 제작해주셔서 감사합니다.
제작자분이 한국분이신 것 같아 일단 한국어와 영어로 글을 올려봅니다.

제가 사용중에 한가지 문제가 발생해서 한번 여쭈어봅니다.
저는 현재 안드로이드에서 Narrate(Dayone 데이터 호환)앱으로 일기를 쓰고 있으며, 일기 데이터를 Dropbox에 저장하여 동기화하고 있습니다. 또한 이 데이터를 윈도우용 Dropbox 클라이언트를 통해 폴더에 동기화시키고, 이를 Journaley에서 위치를 지정해서 사용하고 있습니다.

그런데 한가지 문제가, 해당 폴더에서 파일이 정상적으로 있음에도 불구하고, Journaley에서 인식을 바로 하지 못하고 있으며, 폴더 내에 있는 파일들(정확하게 말하면 entries)에 있는 파일들을 외부에 옮겼다가 다시 해당 폴더로 옮기면 Journaley에서 인식을 합니다.

하여 버그인 것 같아 이렇게 글을 올립니다.
혹시 추가로 알려드려야 할 사항이 있다면 알려주시면 상세히 설명드리겠습니다.

---

Same things written in English.

I had problem when I use the Journaley in Windows.

I wrote the diary in Narrate for android(compatitable for dayone data), and sync the diary data into Dropbox.

And when I write the diary in Journaley for windows, I sync the dropbox data via windows client and set the default folder in Journaley to dropbox's narrate folder.

The diary data in dropbox's folder is existed well, however, Journaley doesn't recognize the diary entry files. When I move the entry files into other folder and move again into Journaley's folder, Journaley recognize the file at that time.

So, I wrote the bug report for this.
If you need more information related to this, I can help you. 

Thank you.

**Comment by crxtrdude** [comment]
You mean [this](http://narrateapp.com/) Narrate for Android? I'll check it out maybe there are some issues ...

How about you give a sample entry and then share out the xml file?

Open your app's folder in Dropbox and then see if they use xml files. Plus does Journaley recognize it at all in the first place?

**Comment by yyoon** [comment]
안녕하세요. 버그 리포트 감사합니다. 몇 가지 더 궁금한 점이 있네요.
파일들을 다른 곳으로 옮겼다가 다시 가져오면 인식한다고 하셨는데,
Journaley가 실행중인 상태에서 파일을 옮기신 것인가요?
그리고 파일들이 아예 하나도 인식이 안되는지, 아니면 몇몇 파일들만 안되는 것인지도 궁금합니다.
인식이 한번 제대로 된 상태에서 Narrate를 통해서 글을 쓰면 다시 Journaley에서 인식 못하는 상황이 재발하나요?

그리고 혹시 `%APPDATA%\Journaley\error.log` 이 파일에 특별한 에러 메시지 같은 것이 없는지 확인 부탁드리겠습니다.

감사합니다.

---

@crxtrdude Yes, that's the Narrate for Android app and AFAIK it also uses the same format Day One uses. I'll also check this out myself, too.

**Comment by crxtrdude** [comment]
Unfortunately, to use their dropbox sync, you need to have Pro. Good thing my cellphone provider can do in-app purchases on Google Play with a prepaid account, I'll try buying the pro version.

Also, if Narrate would work, we could add it support in the readme or the site, with the requirement that it needs the pro version of the app to do so.

**Comment by crxtrdude** [comment]
Just tested the Dropbox sync of Narrate Pro (my very first in-app purchase) and actually works well as Day One. Narrate actually is as similar to Day One with Google Material based UI, albeit their Markdown capabilities are a bit short (no images and no tables as per my test entry).

To sync it, I use the 'Set Dropbox sync folder' to the Day One apps, which is Day One's default folder, which my sync folder from Journaley is set to. ~~I think he didn't set Journaley's folder to the Narrate Sync folder (which by default is Dropbox/apps/Narrate) that's why it didn't read.~~

EDIT: Re-read the OP. Forgot that he did set Journaley's folder to Narrate's. Did he set it in the 'entries' folder or just the folder itself?

I made an entry using Narrate and synced it over to Dropbox. When used in Journaley, it did read it as well as Day One.

Difference is:
- Creator key is above the entry key, similar to Day One
- Of course the 'Software Agent' is Narrate.
- 'Host Name' is Narrate.
- Narrate has a 'Modified date' not formatted similarly to the creation date. (Raw date format)

BTW, Journaley's entries have no timezone, which all apps add to the entries.

So there needs to be a clause in the readme or in the site that you need to make sure that Narrate is syncing in a folder where Journaley would also sync as well and vice versa.

**Comment by yyoon** [comment]
@crxtrdude Thanks for testing it thoroughly. Here are my takes.

Those small differences between Narrate and Journaley entries are either negligible or expected, but let's create an issue for adding timezone for entries created from Journaley.

I don't agree on your last point though. I would consider someone who thinks about syncing journal entries between Day One, Journaley, Narrate via Dropbox is a power user, and it should be obvious to them that the apps should be pointing to the same folder. The OP did configure the folder correctly, so that's not the problem here.

I think we need more information, so let's wait for his response.

**Comment by crxtrdude** [comment]
You got a point on the last one though. We'll wait for his reply. I think you're better in communicating with him on this one though (if it sounds offensive, sorry bout that), but at least I did my part for this problem.

BTW, I might make a little document on what keys Day One currently has in its XML format, which apparently we didn't have here, if it's okay with you?

**Comment by yyoon** [comment]
Sure thing. We could then discuss what to support among those keys.

**Comment by kihyen** [comment]
Every problem is completed when I changed the sync folder from Default to Day one in Narrate Android App.

Maybe the timezone problem could be faced later, but I don't have any problem with that.

제가 동기화할 폴더를 Narrate 안드로이드 앱 설정에서 기본값으로 Dayone으로 바꾸어주니 바로 사용이 가능했습니다. 혹시 FAQ 문서를 만드실 일이 있으시다면 이 내용을 추가로 해둔다면 다른 사용자들에게도 도움이 될 것 같습니다 :)

Thank you for all @crxtrdude  @yyoon

**Comment by yyoon** [comment]
@Dozen7 Thanks a lot! Maybe we should support Narrate-created files without `.doentry` extension in the future. I'll add this information as an FAQ.

해결되셨다니 다행이고, 다시 한 번 제보 감사합니다 :)
