### ISSUE TITLE
Day One generates hundreds of duplicate entries after Journaley is used.

### ISSUE THREAD

**Issue by transientuser** [yyoon/Journaley#137]
If I open Journaley, even if I make no changes, then close it, Day One will create ~230 duplicate entries the next time I open it.   I now have 1200 entries instead of 200 which means that my database is now effectively trash as I am unlikely to spend the time to fix it.

Interestingly, Journaley mostly does not show these duplicate entries, they are visible only in Day One.  While normally I would call that a Day One issue, it only happens if Journaley has been run.

Windows 7 PC, non-administrator account, Journaley 2.1  Unsure of what log files to gather.  I do have some dump files which were from when I had journaley open when Day One was open (won't do that again).

Any suggestions?  I am finally going to make a backup of the database (yes, should have done it an hour ago... water under the bridge) and see if I can use a duplicate file finder without breaking the picture linkage (or just leaving the duplicate pictures.

**Comment by crxtrdude** [comment]
Did you try a more recent Journaley? I think @sguergachi has some new release builds, more recent than 2.1 (but not really recent).

BTW, Sammy, I just tagged you to make you aware of this.

> Interestingly, Journaley mostly does not show these duplicate entries, they are visible only in Day One. While normally I would call that a Day One issue, it only happens if Journaley has been run.

Anyway, Day One's format is interesting in that it uses UUIDs to make sure that duplicates would not be added.

I think that Journaley checks the UUIDs inside the file, instead of the filename, which should correspond to the inside UUID. Pictures of course have their file names as UUID and should correspond with a post with the same UUID.

Trying a newer version of Journaley on a test computer could determine if it still persists on the later versions.

**Comment by sguergachi** [comment]
2.1 is the latest release build. I wouldn't recommend using dev builds in general, and right now there isn't much new stuff in there anyways. I've been super busy and most of the work that needs to be done for the next release is in @yyoon hands.

I have had this happen to me during development once. Haven't been able to reproduce it since, so didn't consider it a bug worth reporting. If there are reproducible steps to get this to happen we could track this bug down much faster.

**Comment by crxtrdude** [comment]
Oh, okay, but I agree with you on the reproducible steps part.

**Comment by transientuser** [comment]
How about the following:
- I will identify one of the records that is chronically replicated.  
- Clean out my Day One folder on dropbox and only have this one record.
- Attempt to reproduce the issue with consistency.
- Document the steps and provide the record.
- If I feel really motivated, I will install a clean Day One client on another device and verify the replication.

**Comment by sguergachi** [comment]
That would be super helpful if you find the time to do that. Thank you.

## 

Sammy Guergachi

**Comment by transientuser** [comment]
Just for yucks, I deleted the DayOne App and re-added.  That seemed to clear the problem up.  I will be more careful with having DayOne and Journaley open at the same time but if it happens again, I will follow the steps I indicated above and provide data.  

Thanks!

**Comment by yyoon** [comment]
Sorry for the trouble you had, and hopefully it won't happen again. Thanks for reporting!

**Comment by sguergachi** [comment]
It's probably also worth mentioning this might be caused by DayOne after seeing the recent updates to the app:
![](http://i.imgur.com/kUuO4KR.jpg)
