### ISSUE TITLE
The Death of Journaley as a Day One Companion App?

### ISSUE THREAD

**Issue by Faterson** [yyoon/Journaley#138]
Hello,

I fear the worst, and I'm just writing here to confirm my fears. Is Journaley now a dead app for those of us who upgraded to the most recent Day One 2 app? Day One 2 offers only one syncing option – Day One syncing service. Dropbox can no longer be used for Day One 2. This likely means Journaley can no longer be used on Windows for those of us who use Day One 2 as their primary journaling software. I'm really sorry about that, but Day One 2 brings important improvements, such as multiple journals (a crucial feature for me), so I was "forced" to upgrade from Day One Classic.

Please let me know if my perception is incorrect and if Journaley can still be used somehow in conjunction with Day One 2. Thank you.

**Comment by sguergachi** [comment]
Sadly you're interpretation is indeed correct. I wouldn't go so far as to say it marks the death of Journaley, it would be wrong to assume that everyone who used Day One classic upgraded to Day One 2. But as you explained, since Day One 2 uses a proprietary sync engine we can't do much on our end. 

We are still committed to working on Journaley, unfortunately both me and @yyoon have busy lives, so we haven't been able to work on it lately. My hope is that we can work on it this summer. 

In terms of Windows support for Day One 2, I would expect the Day One team to build a universal Windows app in the future, I've heard an Android app is on the way so a Windows app doesn't seem to far fetched.  

I'm sorry we can't help you in this case, If Day One 2 sync comes out with a public API or decide to support a cross platform sync engine then we would consider adding support to it in Journaley. As of now our hands are tied.

**Comment by Faterson** [comment]
Thank you for the confirmation, although it's bad news, and above all thank you for the years in which Journaley served me very well. 

Really the best benefit for me of upgrading to Day One 2 is that there now appears to be a brand-new IFTTT channel for Day One which accomplishes certain things that were unthinkable previously, I believe, such as submitting new Day One entries via email. So, when I'm at my Windows computer now, I can submit new Day One entries simply by emailing them to the dedicated IFTTT address. That is a one-way street, of course – I will miss the ability to browse and edit my existing Day One entries on the Windows computer, but I will need to live with that for now, until one of the solutions you mention perhaps is implemented in future. 

Thank you once again for Journaley.
