### ISSUE TITLE
Improve entries listbox scrolling performance

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#22]
Test loading of ~ 1000 entries to see how it affects main UI.

**Comment by yyoon** [comment]
I just finished testing Journaley with 1000 randomly generated entries, each having an attached photo. It takes about 1~2 seconds to launch Journaley, and it turns out scrolling through the 1000 entries is very smooth.

At some point, we would need to make it faster to launch the main app window by loading the entries asynchronously, but it would be a lot of work and error-prone.

For the record, I took random text from www.randomtext.me/api/gibberish/p-5/25-45, and random photos from Flickr to generate the journal entries.

**Comment by sguergachi** [comment]
Do you have an SSD? I noticed it got better after I upgraded, but previously, if I took the scroll bar with the mouse and moved it all the way up and down, it felt like it stuttered a lot usually because of the images.

**Comment by yyoon** [comment]
Yes, I have an SSD, and you're right that a HDD can slow down the scroll quite a bit. I will at least try loading the images in the entry list box asynchronously.

**Comment by yyoon** [comment]
Okay. Now I've changed the code a little bit to load the thumbnail image from a background thread. Initially, the thumbnail would not appear in the list box (while the thumbnail image area is reserved), and once the image loading from disk is complete, the entry will redraw itself to display the thumbnail. Hopefully this change will make scrolling much smoother even with a journal database stored in a hard disk.

**Comment by sguergachi** [comment]
I will test on a HDD computer and report back.



-
Sammy Guergachi

**Comment by sguergachi** [comment]
Works perfectly in HDD drive.
