### ISSUE TITLE
Location and Weather metadata from Day One is whipped when edited in Journaley

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#96]
Referring to bug described in #77.

1. Edit an entry in Day One by inserting a location and weather. 
2. Open that entry in Journaley and make an edit.
3. Weather and location not visible for that entry in Day One.

**Comment by yyoon** [comment]
Whoops. This probably has something to do with the code we accepted from #53. I'll see what I can do with this.

**Comment by yyoon** [comment]
40a04f3 should fix this. @sguergachi Can you test if it preserves the metadata correctly on your side?

**Comment by sguergachi** [comment]
Works for me.

-Sammy Guergachi
On 7/28/2015 11:33:17 PM, YoungSeok Yoon <notifications@github.com> wrote:
40a04f3 [https://github.com/yyoon/Journaley/commit/40a04f30192265b17e22e8a011ec7b92527ac2be] should fix this. @sguergachi [https://github.com/sguergachi] Can you test if it preserves the metadata correctly on your side?

**Comment by FlyingSinger** [comment]
Very cool! Thanks for fixing this! I just did a multi-round-trip test and it works great -- so now I can use Day One and Journaley interchangeably for new entries and for editing previous entries with no data loss. This is especially nice when I need to write something and can't dictate to Siri (like at work). Typically I type the entry in email, pick up the email on iPhone or iPad, and copy/paste it there. Not difficult, but this is much better!

Thanks,
Bruce

**Comment by sguergachi** [comment]
Thanks! The best thing you could do for us right now is to use Journaley as extensively as possible and report any other bugs you find. We want to make sure Journaley is probably tested before we explicitly start promoting it to people outside of github. Any help in making sure Journaley is the best it can be would be greatly appreciated.

## 

Sammy Guergachi

**Comment by yyoon** [comment]
@FlyingSinger Great to hear that! Please feel free to let us know if you have other issues.

**Comment by FlyingSinger** [comment]
I've been writing 2-4 entries a day recently and I will create and edit as many as possible on Journaley now that it preserves all the Day One metadata. I'm on my PC almost as much as my iPhone and iPad so this should be feasible. :)

Thanks again! You guys probably saved me a thousand bucks, because just a few days before I found Journaley, I had seriously started to look at Mac notebooks as an alternate journaling platform (complicated reasons). I like Macs but have no real need for one other than Day One, so I decided to make a last search to see if there might be a Windows version of Day One coming (looks like no). But I found your project, and it's great!
