### ISSUE TITLE
Pressing Alt+Space or clicking on the icon should show the System menu

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#98]
This is a piece of feedback I got. This comes for free if we were to use a normal Windows chrome, but since it's custom we have to implement it ourselves. 

It's easy to test on any native desktop app to see what the System menu is.

**Comment by yyoon** [comment]
This should work in all the following situations:
* Pressing Alt + Space
* Left-clicking on the app icon in the upper left side
* Right-clicking on the titlebar area

**Comment by sguergachi** [comment]
This issue is still persistent in Windows 10. None of the 3 ways of accessing the system menu work.

**Comment by sguergachi** [comment]
nevermind, wasn't running the latest version.

**Comment by sguergachi** [comment]
BaseJournaleyForm should also implement this.

**Comment by yyoon** [comment]
It is implemented in `BaseJournaleyForm`. It's working in all forms (including `WelcomeForm`, `PasswordInputForm`) except for `SettingsForm`. I've investigated this issue a little bit, and it turns out the system menu doesn't even exist when the form's `ShowInTaskbar` property is set to `false`. In other words, the system wouldn't have appeared in the `SettingsForm` even if we were using the Windows default chrome.

**Comment by sguergachi** [comment]
Alright, will close this for good then.
